stages:
    - test

before_script:
    - apt-get update
    - apt-get -y install build-essential make autoconf gcc gnuplot
    - make

test:
    stage: test
    script:
        - make test
        - cd tests
        - gnuplot "tempos.plot"
        - gnuplot medias.plot
    artifacts:
        paths:
            - tests/tabuleiros.txt
            - tests/tempos.txt
            - tests/medias.txt
            - tests/tempos.png
            - tests/medias.png
    tags:
        - ubuntu
