stages:
    - test

before_script:
    - apt-get install build-essential
    - make

run_tests:
    stage: test
    script:
        - make test
    artifacts:
        paths:
            - tests/tabuleiros.txt
    tags:
        - ubuntu
