stages:
    - test

before_script:
    - apt-get update
    - apt-get -y install build-essential make autoconf gcc
    - make

run_tests:
    stage: test
    script:
        - make test
        - cd tests
        - gnuplot "tempos.plot"
    artifacts:
        paths:
            - tests/tabuleiros.txt
            - tests/tempos.txt
            - tests/tempos.png
    tags:
        - ubuntu
