stages:
    - test

before_script:
    - apt-get update
    - apt-get -y install build-essential make autoconf gcc
    - make

run_tests:
    stage: test
    script:
        - make test
    artifacts:
        paths:
            - tests/tabuleiros.txt
    tags:
        - ubuntu
